default-rule-path: /etc/suricata/rules

rule-files:
  - local.rules
  - http-events.rules
  - dns-events.rules
  - ssh-events.rules

af-packet:
  - interface: enp0s8
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    ring-size: 200000
    block-size: 1048576
    copy-mode: tap
    tso: yes

outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: /var/log/suricata/eve.json
      types:
        - alert:
        - http:
        - dns:
        - tls:
        - flow
  - fast:
      enabled: yes
      filename: /var/log/suricata/fast.log
